max_width = 800
nosePoints = [2, 9, 129, 358]  # GIU, SU, SX, DX
faceShapePoints = [152, 10, 234, 454, 136, 365]  # GIU. SU, SX, DX, SX_GIU, DX_GIU
rightEyePoints = [23, 27, 130, 243]  # GIU, SU, SX, DX
rightEyeBrowPoints = [
    46,
    55,
    52,
    65,
    70,
    107,
    105,
    66,
]  # GIU_SX, GIU_DX, GIU_CENT_SX, GIU_CENT_DX, SU_SX, SU_DX, SU_CENT_SX, SU_CENT_DX
leftEyePoints = [253, 257, 463, 359]  # GIU, SU, SX, DX
leftEyeBrowPoints = [
    285,
    276,
    282,
    295,
    336,
    300,
    334,
    296,
]  # GIU_SX, GIU_DX, GIU_CENT_SX, GIU_CENT_DX, SU_SX, SU_DX, SU_CENT_SX, SU_CENT_DX
lipsPoints = [17, 0, 61, 291]  # GIU, SU, SX, DX

points = [
    nosePoints,
    faceShapePoints,
    rightEyePoints,
    rightEyeBrowPoints,
    leftEyePoints,
    leftEyeBrowPoints,
    lipsPoints,
]



chinSlidersValue = {"width": [], "bones": []}

foreheadSlidersValue = {"scale-vert": []}

eyebrowsSlidersValue = {"angle": [], "trans-down": []}

eyesSlidersValue = {
    "height1": [],
    "height2": [],
    "height3": [],
    "trans-in": [],
    "trans-down": [],
    "scale-decr": [],
}

noseSlidersValue = {
    "trans-down": [],
    "trans-in": [],
    "scale-vert": [],
    "scale-horiz": [],
    "width1": [],
    "width2": [],
    "width3": [],
    "septumangle-decr": [],
    "flaring-decr": [],
}

mouthSliderValue = {
    "scale-horiz": [],
    "lowerlip-height": [],
    "upperlip-height": [],
    "cupidsbow-width": [],
    "cupidsbow-decr": [],
}

headSliderValue = {"fat": []}

makeHumanValues = [
    "head/head-age-decr|incr",
    "head/head-angle-in|out",
    "head/head-fat-decr|incr",
    "head/head-invertedtriangular",
    "head/head-scale-depth-decr|incr",
    "head/head-scale-horiz-decr|incr",
    "head/head-scale-vert-decr|incr",
    "head/head-trans-in|out",
    "head/head-trans-down|up",
    "head/head-trans-backward|forward",
    "head/head-back-scale-depth-decr|incr",
    "forehead/forehead-trans-backward|forward",
    "forehead/forehead-scale-vert-decr|incr",
    "forehead/forehead-nubian-decr|incr",
    "forehead/forehead-temple-decr|incr",
    "eyebrows/eyebrows-trans-backward|forward",
    "eyebrows/eyebrows-angle-down|up",
    "eyebrows/eyebrows-trans-down|up",
    "eyes/r-eye-bag-decr|incr",
    "eyes/r-eye-bag-height-decr|incr",
    "eyes/r-eye-bag-in|out",
    "eyes/r-eye-eyefold-angle-down|up",
    "eyes/r-eye-epicanthus-in|out",
    "eyes/r-eye-eyefold-concave|convex",
    "eyes/r-eye-eyefold-down|up",
    "eyes/r-eye-height1-decr|incr",
    "eyes/r-eye-height2-decr|incr",
    "eyes/r-eye-height3-decr|incr",
    "eyes/r-eye-push1-in|out",
    "eyes/r-eye-push2-in|out",
    "eyes/r-eye-trans-in|out",
    "eyes/r-eye-trans-down|up",
    "eyes/r-eye-scale-decr|incr",
    "eyes/r-eye-corner1-down|up",
    "eyes/r-eye-corner2-down|up",
    "eyes/l-eye-bag-decr|incr",
    "eyes/l-eye-bag-in|out",
    "eyes/l-eye-bag-height-decr|incr",
    "eyes/l-eye-eyefold-angle-down|up",
    "eyes/l-eye-epicanthus-in|out",
    "eyes/l-eye-eyefold-concave|convex",
    "eyes/l-eye-eyefold-down|up",
    "eyes/l-eye-height1-decr|incr",
    "eyes/l-eye-height2-decr|incr",
    "eyes/l-eye-height3-decr|incr",
    "eyes/l-eye-push1-in|out",
    "eyes/l-eye-push2-in|out",
    "eyes/l-eye-trans-in|out",
    "eyes/l-eye-trans-down|up",
    "eyes/l-eye-scale-decr|incr",
    "eyes/l-eye-corner1-down|up",
    "eyes/l-eye-corner2-down|up",
    "nose/nose-trans-down|up",
    "nose/nose-trans-backward|forward",
    "nose/nose-trans-in|out",
    "nose/nose-scale-vert-decr|incr",
    "nose/nose-scale-horiz-decr|incr",
    "nose/nose-scale-depth-decr|incr",
    "nose/nose-nostrils-width-decr|incr",
    "nose/nose-point-width-decr|incr",
    "nose/nose-base-down|up",
    "nose/nose-width1-decr|incr",
    "nose/nose-width2-decr|incr",
    "nose/nose-width3-decr|incr",
    "nose/nose-compression-compress|uncompress",
    "nose/nose-curve-concave|convex",
    "nose/nose-greek-decr|incr",
    "nose/nose-hump-decr|incr",
    "nose/nose-volume-decr|incr",
    "nose/nose-nostrils-angle-down|up",
    "nose/nose-point-down|up",
    "nose/nose-septumangle-decr|incr",
    "nose/nose-flaring-decr|incr",
    "mouth/mouth-scale-horiz-decr|incr",
    "mouth/mouth-scale-vert-decr|incr",
    "mouth/mouth-scale-depth-decr|incr",
    "mouth/mouth-trans-in|out",
    "mouth/mouth-trans-down|up",
    "mouth/mouth-trans-backward|forward",
    "mouth/mouth-lowerlip-height-decr|incr",
    "mouth/mouth-lowerlip-width-decr|incr",
    "mouth/mouth-upperlip-height-decr|incr",
    "mouth/mouth-upperlip-width-decr|incr",
    "mouth/mouth-cupidsbow-width-decr|incr",
    "mouth/mouth-angles-down|up",
    "mouth/mouth-lowerlip-middle-down|up",
    "mouth/mouth-lowerlip-volume-decr|incr",
    "mouth/mouth-philtrum-volume-decr|incr",
    "mouth/mouth-upperlip-volume-decr|incr",
    "mouth/mouth-upperlip-ext-down|up",
    "mouth/mouth-upperlip-middle-down|up",
    "mouth/mouth-cupidsbow-decr|incr",
    "chin/chin-jaw-drop-decr|incr",
    "chin/chin-cleft-decr|incr",
    "chin/chin-prominent-decr|incr",
    "chin/chin-width-decr|incr",
    "chin/chin-height-decr|incr",
    "chin/chin-bones-decr|incr",
    "chin/chin-prognathism-decr|incr",
    "cheek/l-cheek-volume-decr|incr",
    "cheek/l-cheek-bones-decr|incr",
    "cheek/l-cheek-inner-decr|incr",
    "cheek/l-cheek-trans-down|up",
    "cheek/r-cheek-volume-decr|incr",
    "cheek/r-cheek-bones-decr|incr",
    "cheek/r-cheek-inner-decr|incr",
    "cheek/r-cheek-trans-down|up",
]
